In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import plotly.express as px


In [2]:
data=pd.read_csv("hepatitis.csv",na_values="?")

In [3]:
data.head()

ID  target  age  gender  steroid  antivirals  fatigue  malaise  anorexia  \
0   1       2   30       2      1.0           2      2.0      2.0       2.0   
1   2       2   50       1      1.0           2      1.0      2.0       2.0   
2   3       2   78       1      2.0           2      1.0      2.0       2.0   
3   4       2   31       1      NaN           1      2.0      2.0       2.0   
4   5       2   34       1      2.0           2      2.0      2.0       2.0   

   liverBig  ...  spleen  spiders  ascites  varices  bili    alk   sgot  albu  \
0       1.0  ...     2.0      2.0      2.0      2.0   1.0   85.0   18.0   4.0   
1       1.0  ...     2.0      2.0      2.0      2.0   0.9  135.0   42.0   3.5   
2       2.0  ...     2.0      2.0      2.0      2.0   0.7   96.0   32.0   4.0   
3       2.0  ...     2.0      2.0      2.0      2.0   0.7   46.0   52.0   4.0   
4       2.0  ...     2.0      2.0      2.0      2.0   1.0    NaN  200.0   4.0   

   protime  histology  
0      NaN          1  
1      NaN          1  
2      NaN          1  
3     80.0          1  
4      NaN          1  

[5 rows x 21 columns]

In [4]:
data.dtypes

ID              int64
target          int64
age             int64
gender          int64
steroid       float64
antivirals      int64
fatigue       float64
malaise       float64
anorexia      float64
liverBig      float64
liverFirm     float64
spleen        float64
spiders       float64
ascites       float64
varices       float64
bili          float64
alk           float64
sgot          float64
albu          float64
protime       float64
histology       int64
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          155 non-null    int64  
 1   target      155 non-null    int64  
 2   age         155 non-null    int64  
 3   gender      155 non-null    int64  
 4   steroid     154 non-null    float64
 5   antivirals  155 non-null    int64  
 6   fatigue     154 non-null    float64
 7   malaise     154 non-null    float64
 8   anorexia    154 non-null    float64
 9   liverBig    145 non-null    float64
 10  liverFirm   144 non-null    float64
 11  spleen      150 non-null    float64
 12  spiders     150 non-null    float64
 13  ascites     150 non-null    float64
 14  varices     150 non-null    float64
 15  bili        149 non-null    float64
 16  alk         126 non-null    float64
 17  sgot        151 non-null    float64
 18  albu        139 non-null    float64
 19  protime     88 non-null     f

In [6]:
data.isnull().sum()

ID             0
target         0
age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig      10
liverFirm     11
spleen         5
spiders        5
ascites        5
varices        5
bili           6
alk           29
sgot           4
albu          16
protime       67
histology      0
dtype: int64

In [7]:
cols=data.columns
cols

Index(['ID', 'target', 'age', 'gender', 'steroid', 'antivirals', 'fatigue',
       'malaise', 'anorexia', 'liverBig', 'liverFirm', 'spleen', 'spiders',
       'ascites', 'varices', 'bili', 'alk', 'sgot', 'albu', 'protime',
       'histology'],
      dtype='object')

In [8]:
data.target.value_counts()

2    123
1     32
Name: target, dtype: int64

In [9]:
data.age.unique()

array([30, 50, 78, 31, 34, 51, 23, 39, 32, 41, 47, 38, 66, 40, 22, 27, 42,
       25, 49, 58, 61, 62, 26, 35, 37, 20, 65, 52, 33, 56, 28, 36, 44, 64,
       45, 57, 24, 67, 59, 60, 48, 54,  7, 69, 72, 70, 46, 53, 43],
      dtype=int64)

In [10]:
for var in cols:
 print(data[var].unique())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155]
[2 1]
[30 50 78 31 34 51 23 39 32 41 47 38 66 40 22 27 42 25 49 58 61 62 26 35
 37 20 65 52 33 56 28 36 44 64 45 57 24 67 59 60 48 54  7 69 72 70 46 53
 43]
[2 1]
[ 1.  2. nan]
[2 1]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 1.  2. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2. nan  1.]
[1.  0.9 0.7 nan 1.3 2.2 2.  1.2 0.6 0.4 0.8 1.4 2.3 0.5 0.3 

In [11]:
data.describe().T

count        mean        std   min    25%   50%     75%    max
ID          155.0   78.000000  44.888751   1.0  39.50  78.0  116.50  155.0
target      155.0    1.793548   0.406070   1.0   2.00   2.0    2.00    2.0
age         155.0   41.200000  12.565878   7.0  32.00  39.0   50.00   78.0
gender      155.0    1.103226   0.305240   1.0   1.00   1.0    1.00    2.0
steroid     154.0    1.506494   0.501589   1.0   1.00   2.0    2.00    2.0
antivirals  155.0    1.845161   0.362923   1.0   2.00   2.0    2.00    2.0
fatigue     154.0    1.350649   0.478730   1.0   1.00   1.0    2.00    2.0
malaise     154.0    1.603896   0.490682   1.0   1.00   2.0    2.00    2.0
anorexia    154.0    1.792208   0.407051   1.0   2.00   2.0    2.00    2.0
liverBig    145.0    1.827586   0.379049   1.0   2.00   2.0    2.00    2.0
liverFirm   144.0    1.583333   0.494727   1.0   1.00   2.0    2.00    2.0
spleen      150.0    1.800000   0.401340   1.0   2.00   2.0    2.00    2.0
spiders     150.0    1.660000   0.475296   1.0   1.00   2.0    2.00    2.0
ascites     150.0    1.866667   0.341073   1.0   2.00   2.0    2.00    2.0
varices     150.0    1.880000   0.326050   1.0   2.00   2.0    2.00    2.0
bili        149.0    1.427517   1.212149   0.3   0.70   1.0    1.50    8.0
alk         126.0  105.325397  51.508109  26.0  74.25  85.0  132.25  295.0
sgot        151.0   85.894040  89.650890  14.0  31.50  58.0  100.50  648.0
albu        139.0    3.817266   0.651523   2.1   3.40   4.0    4.20    6.4
protime      88.0   61.852273  22.875244   0.0  46.00  61.0   76.25  100.0
histology   155.0    1.451613   0.499266   1.0   1.00   1.0    2.00    2.0

In [12]:
cat_cols=data.columns[data.nunique()<5]
cat_cols


Index(['target', 'gender', 'steroid', 'antivirals', 'fatigue', 'malaise',
       'anorexia', 'liverBig', 'liverFirm', 'spleen', 'spiders', 'ascites',
       'varices', 'histology'],
      dtype='object')

In [13]:
num_cols=data.columns[data.nunique()>=5]
num_cols

Index(['ID', 'age', 'bili', 'alk', 'sgot', 'albu', 'protime'], dtype='object')

In [14]:
data.drop("ID",axis=1,inplace=True)
num_cols=data.columns[data.nunique()>=5]
num_cols

Index(['age', 'bili', 'alk', 'sgot', 'albu', 'protime'], dtype='object')

In [15]:
num_cols = ["age", "bili", "alk", "sgot", "albu", "protime"]
cat_cols = ['gender', 'steroid', 'antivirals', 'fatigue', 'malaise', 'anorexia', 'liverBig',
            'liverFirm', 'spleen', 'spiders', 'ascites', 'varices', 'histology']

In [16]:
data.isna().sum()

target         0
age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig      10
liverFirm     11
spleen         5
spiders        5
ascites        5
varices        5
bili           6
alk           29
sgot           4
albu          16
protime       67
histology      0
dtype: int64

In [17]:
X=data.drop("target",axis=1)
y=data["target"]

In [18]:
X.shape

(155, 19)

In [19]:
y.shape

(155,)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True,random_state=123)

In [22]:
print(f" x train {X_train.shape}")
print(f" x test {X_test.shape}")

print(f" y train {y_train.shape}")
print(f" y test {X_test.shape}")

 x train (124, 19)
 x test (31, 19)
 y train (124,)
 y test (31, 19)


In [23]:
X_train.isna().sum()

age            0
gender         0
steroid        1
antivirals     0
fatigue        1
malaise        1
anorexia       1
liverBig       7
liverFirm      8
spleen         4
spiders        4
ascites        4
varices        4
bili           6
alk           23
sgot           4
albu          13
protime       53
histology      0
dtype: int64

In [24]:
X_test.isna().sum()

age            0
gender         0
steroid        0
antivirals     0
fatigue        0
malaise        0
anorexia       0
liverBig       3
liverFirm      3
spleen         1
spiders        1
ascites        1
varices        1
bili           0
alk            6
sgot           0
albu           3
protime       14
histology      0
dtype: int64

In [25]:
df_cat_train=X_train[cat_cols]
df_cat_test=X_test[cat_cols]

In [26]:
from sklearn.impute import SimpleImputer
modelImput=SimpleImputer(strategy="most_frequent")
df_cat_train=modelImput.fit_transform(df_cat_train)
df_cat_test=modelImput.transform(df_cat_test)

d:\programming\artifical intelligance\Programs\anacondaInstall\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)


In [27]:
df_cat_test=pd.DataFrame(df_cat_test,columns=cat_cols)
df_cat_train=pd.DataFrame(df_cat_train,columns=cat_cols)

In [28]:
df_num_train=X_train[num_cols]
df_num_test=X_test[num_cols]

In [29]:
modelIMput_num=SimpleImputer(strategy="mean")
df_num_train=modelIMput_num.fit_transform(df_num_train)
df_num_test=modelIMput_num.transform(df_num_test)

In [30]:
df_num_train=pd.DataFrame(df_num_train,columns=num_cols)
df_num_test=pd.DataFrame(df_num_test,columns=num_cols)

In [31]:
# Combine numeric and categorical in train
X_train = pd.concat([df_num_train, df_cat_train], axis = 1)

# Combine numeric and categorical in test
X_test = pd.concat([df_num_test, df_cat_test], axis = 1)

In [32]:
X_train.isna().sum()

age           0
bili          0
alk           0
sgot          0
albu          0
protime       0
gender        0
steroid       0
antivirals    0
fatigue       0
malaise       0
anorexia      0
liverBig      0
liverFirm     0
spleen        0
spiders       0
ascites       0
varices       0
histology     0
dtype: int64

In [33]:
X_test.isna().sum()

age           0
bili          0
alk           0
sgot          0
albu          0
protime       0
gender        0
steroid       0
antivirals    0
fatigue       0
malaise       0
anorexia      0
liverBig      0
liverFirm     0
spleen        0
spiders       0
ascites       0
varices       0
histology     0
dtype: int64

In [34]:
X_train.head()

age  bili         alk   sgot  albu     protime  gender  steroid  \
0  70.0   1.7  109.000000  528.0   2.8   35.000000     1.0      1.0   
1  34.0   0.7   70.000000   24.0   4.1  100.000000     2.0      2.0   
2  34.0   1.0  105.306931  200.0   4.0   61.408451     1.0      2.0   
3  47.0   1.0  166.000000   30.0   2.6   31.000000     1.0      2.0   
4  28.0   0.7   74.000000  110.0   4.4   61.408451     1.0      2.0   

   antivirals  fatigue  malaise  anorexia  liverBig  liverFirm  spleen  \
0         2.0      1.0      1.0       1.0       2.0        2.0     2.0   
1         2.0      1.0      1.0       1.0       1.0        1.0     2.0   
2         2.0      2.0      2.0       2.0       2.0        2.0     2.0   
3         2.0      1.0      1.0       2.0       2.0        1.0     2.0   
4         2.0      1.0      1.0       2.0       2.0        2.0     2.0   

   spiders  ascites  varices  histology  
0      2.0      2.0      2.0        2.0  
1      1.0      2.0      2.0        2.0  
2      2.0      2.0      2.0        1.0  
3      1.0      1.0      1.0        2.0  
4      2.0      2.0      2.0        1.0

In [35]:
cat_cols

['gender',
 'steroid',
 'antivirals',
 'fatigue',
 'malaise',
 'anorexia',
 'liverBig',
 'liverFirm',
 'spleen',
 'spiders',
 'ascites',
 'varices',
 'histology']

In [36]:
X_train[cat_cols] = X_train[cat_cols].astype('int')

# Test
X_test[cat_cols] = X_test[cat_cols].astype('int')

In [37]:
# from sklearn.preprocessing import OneHotEncoder
# encoder=OneHotEncoder()
# X_train.loc[:,cat_cols]=encoder.fit_transform(X_train.loc[:,cat_cols])
# X_test.loc[:,cat_cols]=encoder.transform(X_test.loc[:,cat_cols])/

X_train = pd.get_dummies(X_train, columns=cat_cols, drop_first=True)

# Test
X_test = pd.get_dummies(X_test, columns=cat_cols, drop_first=True)

In [38]:
X_train.columns


Index(['age', 'bili', 'alk', 'sgot', 'albu', 'protime', 'gender_2',
       'steroid_2', 'antivirals_2', 'fatigue_2', 'malaise_2', 'anorexia_2',
       'liverBig_2', 'liverFirm_2', 'spleen_2', 'spiders_2', 'ascites_2',
       'varices_2', 'histology_2'],
      dtype='object')

In [39]:
X_test.columns

Index(['age', 'bili', 'alk', 'sgot', 'albu', 'protime', 'gender_2',
       'steroid_2', 'antivirals_2', 'fatigue_2', 'malaise_2', 'anorexia_2',
       'liverBig_2', 'liverFirm_2', 'spleen_2', 'spiders_2', 'ascites_2',
       'varices_2', 'histology_2'],
      dtype='object')

In [40]:
from sklearn.preprocessing import MinMaxScaler
scaledModel=MinMaxScaler()
X_train.loc[:,num_cols]=scaledModel.fit_transform(X_train.loc[:,num_cols])
X_test.loc[:,num_cols]=scaledModel.transform(X_test.loc[:,num_cols])

In [41]:
X_train.head()

age      bili       alk      sgot      albu   protime  gender_2  \
0  0.887324  0.181818  0.326772  1.000000  0.142857  0.177215         0   
1  0.380282  0.051948  0.173228  0.019455  0.452381  1.000000         1   
2  0.380282  0.090909  0.312232  0.361868  0.428571  0.511499         0   
3  0.563380  0.090909  0.551181  0.031128  0.095238  0.126582         0   
4  0.295775  0.051948  0.188976  0.186770  0.523810  0.511499         0   

   steroid_2  antivirals_2  fatigue_2  malaise_2  anorexia_2  liverBig_2  \
0          0             1          0          0           0           1   
1          1             1          0          0           0           0   
2          1             1          1          1           1           1   
3          1             1          0          0           1           1   
4          1             1          0          0           1           1   

   liverFirm_2  spleen_2  spiders_2  ascites_2  varices_2  histology_2  
0            1         1          1          1          1            1  
1            0         1          0          1          1            1  
2            1         1          1          1          1            0  
3            0         1          0          0          0            1  
4            1         1          1          1          1            0

In [42]:
from sklearn.svm import SVC
linear_svm = SVC(kernel='linear', C=1, random_state=0)
linear_svm.fit(X=X_train, y= y_train)

SVC(C=1, kernel='linear', random_state=0)

In [43]:
train_predictions = linear_svm.predict(X_train)
test_predictions = linear_svm.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

TRAIN Conf Matrix : 
 [[18  8]
 [ 6 92]]

TRAIN DATA ACCURACY 0.8870967741935484

Train data f1-score for class '1' 0.7199999999999999

Train data f1-score for class '2' 0.9292929292929293


In [45]:
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))



--------------------------------------


TEST Conf Matrix : 
 [[ 4  2]
 [ 2 23]]

TEST DATA ACCURACY 0.8709677419354839

Test data f1-score for class '1' 0.6666666666666666

Test data f1-score for class '2' 0.92


In [46]:
svc = SVC(kernel='rbf', random_state=42, gamma=0.01, C=1)
svc.fit(X_train,y_train)

SVC(C=1, gamma=0.01, random_state=42)

In [47]:
train_predictions = svc.predict(X_train)
test_predictions = svc.predict(X_test)

### Train data accuracy

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN Conf Matrix : 
 [[ 0 26]
 [ 0 98]]

TRAIN DATA ACCURACY 0.7903225806451613

Train data f1-score for class '1' 0.0

Train data f1-score for class '2' 0.8828828828828829


--------------------------------------


TEST Conf Matrix : 
 [[ 0  6]
 [ 0 25]]

TEST DATA ACCURACY 0.8064516129032258

Test data f1-score for class '1' 0.0

Test data f1-score for class '2' 0.8928571428571428


In [53]:

svc = SVC(kernel='rbf', random_state=123, gamma=0.01, C=1)
svc.fit(X_train,y_train)

SVC(C=1, gamma=0.01, random_state=123)

In [55]:
## Predict
train_predictions = svc.predict(X_train)
test_predictions = svc.predict(X_test)

### Train data accuracy

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN Conf Matrix : 
 [[ 0 26]
 [ 0 98]]

TRAIN DATA ACCURACY 0.7903225806451613

Train data f1-score for class '1' 0.0

Train data f1-score for class '2' 0.8828828828828829


--------------------------------------


TEST Conf Matrix : 
 [[ 0  6]
 [ 0 25]]

TEST DATA ACCURACY 0.8064516129032258

Test data f1-score for class '1' 0.0

Test data f1-score for class '2' 0.8928571428571428


In [50]:
from sklearn.model_selection import GridSearchCV

svc_grid = SVC()

param_grid = {
                'C': [0.001, 0.01, 0.1, 1, 10, 100, 5, 3, 0.02 ],
                'gamma': [ 0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
                'kernel':['linear', 'rbf' , 'guassian','poly'],
             }

svc_cv_grid = GridSearchCV(estimator = svc_grid, param_grid = param_grid, cv = 5, verbose=1)
svc_cv_grid.fit(X=X_train, y=y_train)

Fitting 5 folds for each of 252 candidates, totalling 1260 fits


d:\programming\artifical intelligance\Programs\anacondaInstall\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
315 fits failed out of a total of 1260.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
315 fits failed with the following error:
Traceback (most recent call last):
  File "d:\programming\artifical intelligance\Programs\anacondaInstall\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\programming\artifical intelligance\Programs\anacondaInstall\lib\site-packages\sklearn\svm\_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "d:\programming\artifical 

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 5, 3, 0.02],
                         'gamma': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
                         'kernel': ['linear', 'rbf', 'guassian', 'poly']},
             verbose=1)

In [51]:
svc_best = svc_cv_grid.best_estimator_
svc_best

SVC(C=3, gamma=0.1)

In [52]:
## Predict
train_predictions = svc_best.predict(X_train)
test_predictions = svc_best.predict(X_test)

print("TRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=2))

### Test data accuracy
print("\n\n--------------------------------------\n\n")
print("TEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=2))

TRAIN DATA ACCURACY 0.9112903225806451

Train data f1-score for class '1' 0.7755102040816326

Train data f1-score for class '2' 0.9447236180904524


--------------------------------------


TEST DATA ACCURACY 0.8709677419354839

Test data f1-score for class '1' 0.6666666666666666

Test data f1-score for class '2' 0.92
